//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicEducationDepartment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReferralForm
    {
        public int StudentReferralID { get; set; }
        public long AccountID { get; set; }
        public string StudentName { get; set; }
        public string StudentReferredBy { get; set; }
        public string StudentReasonForReferral { get; set; }
        public string StudentLevelSection { get; set; }
        public string StudentMoodBehaviors { get; set; }
        public string StudentMoodBehaviorOthers { get; set; }
        public string StudentAcademicConcerns { get; set; }
        public string StudentAcademicConcernOthers { get; set; }
        public string StudentRelationship { get; set; }
        public string StudentRelationshipOthers { get; set; }
        public string StudentHomeConcerns { get; set; }
        public string StudentHomeConcernsOthers { get; set; }
        public string StudentInitialActionsTaken { get; set; }
        public Nullable<bool> IsAgreeToReferred { get; set; }
        public string StudentStatus { get; set; }
        public int StudentAcknowledgeById { get; set; }
        public string StudentTo { get; set; }
        public string StudentDesignation { get; set; }
        public string StudentThisIsToInform { get; set; }
        public string StudentWhomReferred { get; set; }
        public string StudentHasStarted { get; set; }
        public string StudentBeingAttended { get; set; }
        public string StudentHisHerStatus { get; set; }
        public string StudentReferredTo { get; set; }
        public Nullable<int> StudentNumberOfFollowUps { get; set; }
        public string StudentTrackingNumber { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
